var LANG_EN = {
	dashboard: "DASHBOARD",
	splash: "SPLASH",
	accounts: "ACCOUNTS",
	analytics: "ANALYTICS",
	banks: "banks",
	bookings: "BOOKINGS",
	enquiries: "ENQUIRIES",
	helps: "helps",
	payments: "payments",
	promotions: "promotions",
	scooters: "SCOOTERS",
	finance: "FINANCE",
	miscellaneous: "MISCELLANEOUS",
	//general functions:
	itemsPerPage: "Items Per Page",
	orderBy: "Order By",
	search: "search",
	//general edition
	activated: "activated",
	deactivated: "deactivated",
	update: "update",
	delete: "delete",	
	pageUp: "prev",
	pageDown: "next",
	//general information
	by: "by",	
	date: "date",
	//accounts
	account: "account",
	email: "email",
	username: "username",
	socialMedia: "social media",
	facebookId: "FacebookID",
	birthday: "birthday",
	createAccount: "Create New Account",
	//scooters
	scooter: "scooter",
	scooterId: "Scooter ID",
	battery: "battery remaining",
	integrateId: "Integrate ID",
	name: "name",
	model: "model",
	tracking: "tracking",
	createScooter: "Create New Scooter",
	//booking
	booking: "booking",
	bookingId: "booking ID",
	startTime: "start time",
	endTime: "end time",
	destination: "destination",
	bookingBy : "booking by",
	outsetlockId: "outsetlock ID",
	destinationlockId : "destinationlock ID",
	remarks : "remarks",
	createBooking: "create new booking",
	//enquiry
	enquiry: "enquiry",
	enquiryId: "enquiry ID",
	comment: "comment",
	//bank
	bank: "bank",
	bankId: "bank ID",
	deposit: "deposit",
	stamps: "stamps",
	cash: "cash",
	createBank: "create new bank",
	//payment
	payment: "payment",
	paymentId: "payment ID",
	method: "method",
	credential1: "credential1",
	credential2: "credential2",
	credential3: "credential3",
	createPayment: "create new payment",
	//promotion
	promotion: "promotion",
	promotionId: "promotion ID",
	description: "description",
	amount: "amount",
	createPromotion: "create new promotion",
	promotionName: "promotion name",
	//help
	help: "help",
	helpId: "help ID",
	order: "order",
	createHelp: "create new help",
	content: "content",
	title: "title"


	//
};

var LANG_CH = {
	dashboard: "控制台",
	splash: "启动页",
	account: "用户",
	analytics: "统计信息",
	bank: "账户",
	booking: "订单",
	enquiry: "用户询问",
	help: "帮助",
	payment: "支付",
	promotion: "优惠",
	scooter: "踏板车",
	finance: "财务",
	miscellaneous: "其他",

	//基本功能:
	itemsPerPage: "每页数量",
	orderBy: "排序",
	search: "检索",
	//基本编辑：
	activated: "已激活",
	deactivated: "未激活",
	update: "更新",
	delete: "删除",	
	pageUp: "上一页",
	pageDown: "下一页",
	//基本信息：
	by: "属于",	
	date: "日期",
	//账户相关
	account: "账户",
	email: "电邮",
	username: "用户名",
	socialMedia: "社交网路",
	facebookId: "脸书账号",
	birthday: "生日",
	createAccount: "新增",
	//踏板车相关
	scooter: "踏板车",
	scooterId: "踏板车编码",
	battery: "剩余电量",
	integrateId: "集成编码",
	name: "名字",
	model: "型号",
	tracking: "位置信息",
	createScooter: "新增",
	//预定相关
	booking: "预定",
	bookingId: "预定编码",
	startTime: "开始时间",
	endTime: "结束时间",
	destination: "目的地",
	bookingBy : "预定人",
	outsetlockId: "起始锁",
	destinationlockId : "终点锁",
	remarks : "备注",
	createBooking: "新增",
	//问询相关
	enquiry: "问询",
	enquiryId: "问询编码",
	comment: "评论",
	//户头相关
	bank: "户头",
	bankId: "户头编码",
	deposit: "定金",
	stamps: "印章",
	cash: "余额",
	createBank: "新增",
	//支付相关
	payment: "支付",
	paymentId: "支付编码",
	method: "方式",
	credential1: "支付信息1",
	credential2: "支付信息2",
	credential3: "支付信息3",
	createPayment: "新增",
	//促销活动相关
	promotion: "促销活动",
	promotionId: "活动编码",
	description: "描述",
	amount: "优惠额度",
	createPromotion: "新增",
	promotionName: "活动名称",
	//帮助也页相关
	help: "帮助页",
	helpId: "帮助页编码",
	order: "顺序",
	createHelp: "新增",
	content: "内容",
	title: "标题"

};